### ISSUE TITLE
Issues displaying text

### ISSUE THREAD

**Issue by Dids** [grimfang4/nfont#4]
I've been trying to figure out why NFont isn't showing anything when used with SDL_gpu, using a very barebones and minimal code.

I do see the following error on startup:
```
SDL_FontCache ran out of packing space and could not add another cache level.
```

I'm assuming the error is why it's not working?

Not sure if related, but I'm statically linking everything I can (including SDL_ttf), and had to more or less roll my own static library when it came to FreeType, so that might be related, or it might not.

Hoping you can shed some light on this, since this tiny little font library would be an awesome addition. :)

**Comment by Dids** [comment]
Never mind, didn't know I had to initialize the font _after_ SDL_gpu is initialized. Works great now.

**Comment by grimfang4** [comment]
Sorry I couldn't look into this sooner, but I'm glad you figured it out!  Thanks for pointing this out, too.  That error message is not appropriate for this situation, so we should add a check on init to provide a more meaningful error.
