### ISSUE TITLE
Support for loading fonts from byte arrays

### ISSUE THREAD

**Issue by Dids** [grimfang4/nfont#5]
I'm doing something along the lines of this:

```cpp
Resource fontResource = LOAD_RESOURCE(freesans_ttf);
TTF_Font *font = TTF_OpenFontRW(SDL_RWFromMem((void*)fontResource.data(), (int)fontResource.size()), 1, 16);
nfont = NFont(font, NFont::Color(0, 200, 0, 255));
```

Also tried the following:

```cpp
Resource fontResource = LOAD_RESOURCE(freesans_ttf);
nfont = NFont(SDL_RWFromMem((void*)fontResource.data(), (int)fontResource.size()), 1, 16, NFont::Color(0, 200, 0, 255));
```

While I'm not getting any errors, I'm also not seeing any text being rendered. If I load the font from the filesystem, everything works, but in this specific case I'm embedding a few static resources to the compiled executable, then loading resources (such as this font) from it.

Other resources, such as images, load just fine, so I'm assuming it's an issue with either TTF_Font or NFont, but I might be missing something, so figured I'd finally open an issue about it (been struggling with this one for months).

I really hope you're still around and/or working on NFont, as this is currently the only issue I have with it, everything else works perfectly. :)

**Comment by Dids** [comment]
Just to update on this: it works fine, and it was most likely something I did, as it just magically started working. ;)

**Comment by grimfang4** [comment]
Oh yeah, sorry I didn't get back to you on this.  This is good news!
