### ISSUE TITLE
UTF8 characters not showing

### ISSUE THREAD

**Issue by ryancheung** [grimfang4/nfont#6]
OS: Ubuntu 18.04 Desktop
OpenGL 4.0

```
    SDL_RWops* fontRWops = SDL_RWFromConstMem(&simsun_ttc[0], simsun_ttc_len);
    NFont font(fontRWops, 0, 22, NFont::Color(0,0,200,255));

    font.draw(target, 0, 0, NFont::Scale(0.85f), "UTF-8 text: %sXXXXXXX", utf8_string.c_str());
```

utf8_string: `Hello 你好世界, world!`

The chinese characters do not showing.
![669854216](https://user-images.githubusercontent.com/240899/50809398-2e779600-133e-11e9-84a7-4530569cc4c0.jpg)

**Comment by ryancheung** [comment]
I tried the code in `~/nfont/test/main.cpp`, fonts in  ~/nfont/test/fonts/, and utf8_sample.txt: `Μπορώ να φάω σπασμένα γυαλιά χωρίς να πάθω τίποτα.`.
It does not work also:

![2019-01-08 12-56-23](https://user-images.githubusercontent.com/240899/50810483-d5f7c700-1344-11e9-8d5e-676735453dd9.png)

**Comment by ryancheung** [comment]
If I do not use SDL_gpu as renderer, it works correctly:

![2019-01-08 13-03-08](https://user-images.githubusercontent.com/240899/50810735-2ae80d00-1346-11e9-82d6-63737dfc11b8.png)

So the problem come with `#define FC_USE_SDL_GPU`

**Comment by ryancheung** [comment]
Im sure that `SDL_FontCache.c:1491: surf = TTF_RenderUTF8_Blended(font->ttf_source, buff, white);`  render utf8 correctly, i don't know what to do next now.

**Comment by grimfang4** [comment]
It may be something up with SDL_gpu itself.  I'll see if I can put some time into it soon.

**Comment by grimfang4** [comment]
You can try an older revision of SDL_gpu for now, like https://github.com/grimfang4/sdl-gpu/commit/a4ff1ab02410f154b004c29ec46e07b22890fa1f

**Comment by ryancheung** [comment]
@grimfang4 Yeah, older version works correctly, thanks.

**Comment by ryancheung** [comment]
if set `GPU_SetDefaultAnchor(0, 0);` UTF8 text showed would have a weird offset, any suggestions @grimfang4

**Comment by grimfang4** [comment]
Yeah, NFont doesn't anticipate a change to the anchor.  Either NFont needs to set the anchor itself (not a bad change), or you should use GPU_SetAnchor() as needed instead of setting the default.

**Comment by grimfang4** [comment]
Okay, try the latest for that particular bugfix (change is in SDL_FontCache).
